import numpy as np
'''
print(np.__version__)
a = np.array([1,2,3])
print(a)
print(type(a))
b= np.array([[1,2],[3,4]])
print(b)
print(type(b))
print(b.dtype)
c = np.array([[1,2,3],[4,5,6]],'S')
print(c)
print(c.dtype)

arr = np.zeros((2,3),int)
print(arr)
arr = np.ones([2,3],int)
print(arr)

arr = np.ones((4,3),order='F')
print(arr)

arr = np.arange(10)
print("Array",arr)
arr = np.arange(1,10,2)
print(arr)

arr = np.linspace(0,5,num=10)
print(arr)
arr = np.linspace(1,2,num=10,endpoint=False)
print(arr)
arr = np.linspace(1,2,num=10,retstep=True)
print(arr)

arr = np.random.rand(5)
print(arr)
arr = np.random.rand(2,3)
print(arr)
arr = np.random.rand(2,3,4)
print(arr)

arr = np.empty([2,3])
print(arr)
print(arr.dtype)
arr = np.full((2,3),5)
print(arr)
arr = np.full((2,3),'a')
print(arr)
'''
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
print(a)
print(a[0,1,2])
print(a[0,0,-1])

a = np.array([1,2,3,4,5])
print(a[1:5])
print(a[::4])
print(a[-2::-1])
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0:2,2])
print(a[1:3,0:1])